---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for initializing the RDS with SQL scripts on a S3 bucket.
Resources:
  # Create the Oracle RDS
  SecurityGroupSierraRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupSierraRDS
      GroupDescription: Security group for Sierra RDS backend
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 0.0.0.0/0
  SierraRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '10'
      DBInstanceClass: db.t2.micro
      Engine: oracle-ee
      MasterUsername: admin
      MasterUserPassword: p4ssw0rd
      VPCSecurityGroups:
      - !GetAtt SecurityGroupSierraRDS.GroupId
      Tags:
        - Key: Name
          Value: SierraRDS
      
  # Lambda function to initialize RDS with SQL scripts