---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for initializing the RDS with SQL scripts on a S3 bucket.
Parameters:
  DBInstanceName:
    Type: String
    Description: Enter a valid Database instance name (AWS automatically sets this to lowercase)
    MinLength: 1
    MaxLength: 30
    AllowedPattern: "[-_ a-zA-Z0-9]*"
  DBUsername:
    Type: String
    Description: Enter a valid Database username
    MinLength: 1
    MaxLength: 30
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    #===============================================
    #     Minimum password enforced by AWS:
    # MySQL: Must contain from 8 to 41 alphanumeric characters.
    # Oracle: Must contain from 8 to 30 alphanumeric characters.
    # SQL Server: Must contain from 8 to 128 alphanumeric characters.
    #===============================================
  DBPassword:
    Type: String
    Description: Enter a valid Database password (minimum 8 alphanumberic characters)
    NoEcho: true
    MinLength: 8
    MaxLength: 30
    AllowedPattern: "[a-zA-Z0-9]*"
  DBInstanceType:
    Type: String
    Description: Enter one of the possible instance type for database
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large
  DBSecurityGroup:
    Type: String
    Description: Name for the database security group.
    AllowedPattern: "[a-zA-Z0-9]*"
  #===============================================
  #     Storage size ranges enforced by AWS:
  # MySQL, MariaDB, PostgreSQL:
  #   gp2: 20 to 16384
  #   io1: 100 to 16384
  #   standard: 5 to 3072
  # Oracle: 
  #   gp2: 20 to 16384; Single-AZ $0.115 per GB-month/Multi-AZ $0.23 per GB-month
  #   io1: 100 to 16384; Single-AZ $0.125 per GB-month + $0.10 per IOPS-month/Multi-AZ $0.25 per GB-month + $0.20 per IOPS-month
  #   standard: 10 to 3072; Single-AZ $0.10 per GB-month + $0.10 per 1 million requests/Multi-AZ $0.20 per GB-month + $0.10 per 1 million requests
  # SQL Server:
  #   gp2: 20 to 16384
  #   io1: 100 to 16384
  #   standard: 20 to 1024
  #===============================================
  # DBStorageType:
    # Type: String
    # Description: Enter one of the possible instance storage type for database
    # AllowedValues:
      # - General Purpose (SSD) storage (gp2)
      # - Provisioned IOPS storage (io1)
      # - Magnetic storage (standard)
  # DBStorageSize:
    # Type: Number
    # Description: Enter a storage size for database
    # MinValue: 
    # MaxValue:
Resources:
  # Create the Oracle RDS
  SecurityGroupSierraRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 
        Ref: DBSecurityGroup
      GroupDescription: Security group for Sierra RDS backend
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 0.0.0.0/0
  SierraRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '10'
        # Ref: DBStorageSize
      DBInstanceClass:
        Ref: DBInstanceType
      Engine: oracle-ee
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      VPCSecurityGroups:
      - !GetAtt SecurityGroupSierraRDS.GroupId
      StorageType: standard
        # Ref: DBStorageType
      DBInstanceIdentifier:
        Ref: DBInstanceName
      Tags:
        - Key: Name
          Value: SierraRDS
      
  # Lambda function to initialize RDS with SQL scripts
Outputs:
   SierraRDSEndpoint:
     Description: Database endpoint
     Value: !Sub "${SierraRDS.Endpoint.Address}:${SierraRDS.Endpoint.Port}"