---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation stack for initializing the RDS with SQL scripts on a S3 bucket.
Parameters:
  DBUsername:
    Type: String
    Description: Enter a valid Database username
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
  DBPassword:
    Type: String
    Description: Enter a valid Database password
    NoEcho: true
    MinLength: 1
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
  DBInstanceType:
    Type: String
    Description: Enter one of the possible instance type for database
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
      - db.t2.large

Resources:
  # Create the Oracle RDS
  SecurityGroupSierraRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupSierraRDS
      GroupDescription: Security group for Sierra RDS backend
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1521
          ToPort: 1521
          CidrIp: 0.0.0.0/0
  SierraRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '10'
      DBInstanceClass:
        Ref: DBInstanceType
      Engine: oracle-ee
      MasterUsername:
        Ref: DBUsername
      MasterUserPassword:
        Ref: DBPassword
      VPCSecurityGroups:
      - !GetAtt SecurityGroupSierraRDS.GroupId
      Tags:
        - Key: Name
          Value: SierraRDS
      
  # Lambda function to initialize RDS with SQL scripts